# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pricy < Formula
  desc ""
  homepage "https://github.com/stangirard/pricy"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StanGirard/pricy/releases/download/v0.7.1/pricy_0.7.1_Darwin_x86_64.tar.gz"
      sha256 "27c63fb486bbbb8ea19426d6e0c49d3e7f66cfd9c6a3d45dbefd61382f20209b"

      def install
        bin.install "pricy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StanGirard/pricy/releases/download/v0.7.1/pricy_0.7.1_Darwin_arm64.tar.gz"
      sha256 "fd5a011ce17c7ee793d07680883ada442d06671bae164740f152d2f7de99c04f"

      def install
        bin.install "pricy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/StanGirard/pricy/releases/download/v0.7.1/pricy_0.7.1_Linux_x86_64.tar.gz"
      sha256 "7ef41eaa008b53dd02d94e9e81f43ccc9ef8b1b261cc3c50cf873de29f464939"

      def install
        bin.install "pricy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StanGirard/pricy/releases/download/v0.7.1/pricy_0.7.1_Linux_arm64.tar.gz"
      sha256 "10650c3b5e5715f73af85a00948e82a20b217cd3fba26eb0aaf6c2b8a3703478"

      def install
        bin.install "pricy"
      end
    end
  end
end
