# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yatas < Formula
  desc ""
  homepage "https://github.com/stangirard/yatas"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StanGirard/YATAS/releases/download/v0.2.4/YATAS_0.2.4_Darwin_x86_64.tar.gz"
      sha256 "e0d4292c2793ef604c1770e598fb2a1271204e3c4b3c1104b6cd0b833b147edf"

      def install
        bin.install "yatas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StanGirard/YATAS/releases/download/v0.2.4/YATAS_0.2.4_Darwin_arm64.tar.gz"
      sha256 "5595e28d7b8323af528d63f55a32c6dadf02adc7a953e7284e09ef67b8ba5e83"

      def install
        bin.install "yatas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/StanGirard/YATAS/releases/download/v0.2.4/YATAS_0.2.4_Linux_x86_64.tar.gz"
      sha256 "7ae23cb9468adf6dd2a5204d2dd4bf233d5111cb35f9538bcdb50d99e1c2b292"

      def install
        bin.install "yatas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StanGirard/YATAS/releases/download/v0.2.4/YATAS_0.2.4_Linux_arm64.tar.gz"
      sha256 "056c1d006cd8d56cd07add90f5df9d1da675f7f525518999c8be73c8ca5be9d4"

      def install
        bin.install "yatas"
      end
    end
  end
end
